---
- name: Upgrade packages
  become: true
  apt:
    update_cache: yes
    upgrade: safe

# https://github.com/RSS-Bridge/rss-bridge/wiki/Requirements
- name: Install requirements
  apt:
    name: ['openssl',
           'unzip',
    ]
    state: present
    update_cache: yes
    cache_valid_time: 3600
